const fs = require('fs');
const path = require('path');

const speciesArray = `[
  { id: '1', name: 'Sheep', spaceRequired: 20, icon: '🐑', category: 'Livestock', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'Pasture & Hay', growthDays: '150 Days', progressPct: 60, description: 'Provides wool and natural grazing.', companions: ['Goat', 'Guard Dog', 'Chicken', 'Llama', 'Alpaca', 'Pig', 'Collie', 'Mule', 'Donkey', 'Cow', 'Horse'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Beginner Friendly', cost: '$45/mo', water: 'Medium', yieldName: 'Wool', yieldValue: 60 },
  { id: '2', name: 'Goat', spaceRequired: 15, icon: '🐐', category: 'Livestock', sizeClass: 'w-20 h-20', iconSize: 'text-3xl', feedType: 'Brush & Hay', growthDays: '120 Days', progressPct: 75, description: 'Excellent at clearing brush and weeds.', companions: ['Sheep', 'Horse', 'Cow', 'Mule', 'Pig', 'Llama', 'Alpaca', 'Collie', 'Guard Dog', 'Donkey', 'Chicken'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Intermediate', cost: '$40/mo', water: 'Medium', yieldName: 'Milk/Dairy', yieldValue: 55 },
  { id: '3', name: 'Cow', spaceRequired: 60, icon: '🐄', category: 'Livestock', sizeClass: 'w-36 h-36', iconSize: 'text-6xl', feedType: 'Pasture & Silage', growthDays: '700 Days', progressPct: 30, description: 'Large grazing animal.', companions: ['Horse', 'Goat', 'Pig', 'Mule', 'Sheep', 'Donkey', 'Chicken', 'Guard Dog'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Advanced', cost: '$120/mo', water: 'High', yieldName: 'Milk/Dairy', yieldValue: 180 },
  { id: '4', name: 'Buffalo', spaceRequired: 70, icon: '🐃', category: 'Livestock', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Grass & Forage', growthDays: '800 Days', progressPct: 20, description: 'Requires very sturdy fencing.', companions: ['Cow', 'Elephant', 'Ostrich', 'Emu'], enemies: ['Tiger', 'Lion'], careLevel: 'Advanced', cost: '$150/mo', water: 'Very High', yieldName: 'Rich Milk', yieldValue: 220 },
  { id: '5', name: 'Horse', spaceRequired: 80, icon: '🐎', category: 'Livestock', sizeClass: 'w-36 h-36', iconSize: 'text-6xl', feedType: 'Hay & Grain', growthDays: 'Adult', progressPct: 100, description: 'Requires large running space.', companions: ['Goat', 'Cow', 'Donkey', 'Mule', 'Sheep', 'Chicken', 'Cat'], enemies: ['Wolf', 'Bear'], careLevel: 'Advanced', cost: '$200/mo', water: 'High', yieldName: 'Riding/Work', yieldValue: 100 },
  { id: '6', name: 'Donkey', spaceRequired: 40, icon: '🫏', category: 'Working', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Hay & Grass', growthDays: 'Adult', progressPct: 100, description: 'Excellent guard animals for livestock.', companions: ['Sheep', 'Horse', 'Alpaca', 'Cow', 'Llama', 'Mule', 'Goat', 'Chicken'], enemies: ['Wolf'], careLevel: 'Intermediate', cost: '$50/mo', water: 'Low', yieldName: 'Draft/Guard', yieldValue: 80 },
  { id: '7', name: 'Chicken', spaceRequired: 4, icon: '🐔', category: 'Poultry', sizeClass: 'w-12 h-12', iconSize: 'text-xl', feedType: 'Grain & Crumbles', growthDays: '45 Days', progressPct: 85, description: 'Provides daily eggs.', companions: ['Duck', 'Sheep', 'Goat', 'Turkey', 'Goose', 'Quail', 'Peacock', 'Cow', 'Horse', 'Donkey'], enemies: ['Cat', 'Wolf', 'Fox'], careLevel: 'Beginner Friendly', cost: '$15/mo', water: 'Low', yieldName: 'Eggs', yieldValue: 30 },
  { id: '8', name: 'Duck', spaceRequired: 6, icon: '🦆', category: 'Poultry', sizeClass: 'w-14 h-14', iconSize: 'text-2xl', feedType: 'Pellets & Greens', growthDays: '50 Days', progressPct: 65, description: 'Excellent for slug control.', companions: ['Chicken', 'Goose', 'Turkey', 'Peacock', 'Quail', 'Pig'], enemies: ['Cat', 'Wolf', 'Fox'], careLevel: 'Beginner Friendly', cost: '$20/mo', water: 'High', yieldName: 'Eggs/Feathers', yieldValue: 35 },
  { id: '9', name: 'Ostrich', spaceRequired: 45, icon: '🦤', category: 'Poultry', sizeClass: 'w-32 h-32', iconSize: 'text-6xl', feedType: 'Plants & Insects', growthDays: '365 Days', progressPct: 100, description: 'Largest living bird.', companions: ['Emu', 'Kangaroo', 'Camel', 'Buffalo'], enemies: ['Lion', 'Tiger', 'Wolf'], careLevel: 'Advanced', cost: '$80/mo', water: 'Low', yieldName: 'Eggs/Tourism', yieldValue: 120 },
  { id: '10', name: 'Peacock', spaceRequired: 15, icon: '🦚', category: 'Poultry', sizeClass: 'w-20 h-20', iconSize: 'text-4xl', feedType: 'Seeds & Insects', growthDays: '200 Days', progressPct: 90, description: 'Ornamental bird.', companions: ['Chicken', 'Turkey', 'Duck', 'Goose', 'Parrot'], enemies: ['Cat', 'Wolf'], careLevel: 'Intermediate', cost: '$30/mo', water: 'Medium', yieldName: 'Ornamental Feathers', yieldValue: 40 },
  { id: '11', name: 'Guard Dog', spaceRequired: 25, icon: '🐕', category: 'Working', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Meat & Kibble', growthDays: 'Adult', progressPct: 100, description: 'Protects livestock from predators.', companions: ['Sheep', 'Goat', 'Cow', 'Pig', 'Alpaca', 'Llama', 'Chicken', 'Turkey', 'Collie'], enemies: ['Wolf', 'Tiger', 'Cat', 'Bear'], careLevel: 'Intermediate', cost: '$60/mo', water: 'Medium', yieldName: 'Security/Protection', yieldValue: 90 },
  { id: '12', name: 'Cat', spaceRequired: 10, icon: '🐈', category: 'Working', sizeClass: 'w-16 h-16', iconSize: 'text-2xl', feedType: 'Meat & Fish', growthDays: 'Adult', progressPct: 100, description: 'Excellent barn cat.', companions: ['Horse', 'Cow', 'Pig', 'Mule', 'Donkey'], enemies: ['Guard Dog', 'Chicken', 'Parrot', 'Quail', 'Duck', 'Goose'], careLevel: 'Beginner Friendly', cost: '$20/mo', water: 'Low', yieldName: 'Pest Control', yieldValue: 30 },
  { id: '13', name: 'Parrot', spaceRequired: 5, icon: '🦜', category: 'Exotic', sizeClass: 'w-12 h-12', iconSize: 'text-xl', feedType: 'Seeds & Fruits', growthDays: 'Adult', progressPct: 100, description: 'Highly intelligent and vocal.', companions: ['Peacock'], enemies: ['Cat'], careLevel: 'Advanced', cost: '$40/mo', water: 'Low', yieldName: 'Tourism/Breeding', yieldValue: 50 },
  { id: '14', name: 'Camel', spaceRequired: 70, icon: '🐪', category: 'Exotic', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Dry Foliage', growthDays: 'Adult', progressPct: 100, description: 'Desert adapted.', companions: ['Donkey', 'Ostrich', 'Emu', 'Elephant'], enemies: ['Tiger', 'Lion'], careLevel: 'Intermediate', cost: '$90/mo', water: 'Very Low', yieldName: 'Wool/Milk', yieldValue: 140 },
  { id: '15', name: 'Wolf', spaceRequired: 100, icon: '🐺', category: 'Wild', sizeClass: 'w-32 h-32', iconSize: 'text-6xl', feedType: 'Raw Meat', growthDays: 'Adult', progressPct: 100, description: 'Apex pack predators.', companions: [], enemies: ['Guard Dog', 'Sheep', 'Goat', 'Cow', 'Buffalo', 'Horse', 'Pig', 'Llama', 'Alpaca', 'Deer', 'Mule', 'Chicken', 'Duck', 'Ostrich'], careLevel: 'Expert', cost: '$180/mo', water: 'Medium', yieldName: 'Conservation/Eco', yieldValue: 150 },
  { id: '16', name: 'Deer', spaceRequired: 150, icon: '🦌', category: 'Wild', sizeClass: 'w-32 h-32', iconSize: 'text-6xl', feedType: 'Forage & Leaves', growthDays: 'Adult', progressPct: 100, description: 'Flighty herbivores.', companions: ['Kangaroo', 'Emu'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Advanced', cost: '$90/mo', water: 'Medium', yieldName: 'Eco-Tourism', yieldValue: 80 },
  { id: '17', name: 'Tiger', spaceRequired: 200, icon: '🐅', category: 'Wild', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Heavy Meat', growthDays: 'Adult', progressPct: 100, description: 'Massive solitary predators.', companions: [], enemies: ['Cow', 'Buffalo', 'Deer', 'Sheep', 'Goat', 'Horse', 'Pig', 'Camel', 'Elephant'], careLevel: 'Expert', cost: '$300/mo', water: 'High', yieldName: 'Sanctuary Donor ROI', yieldValue: 400 },
  { id: '18', name: 'Elephant', spaceRequired: 500, icon: '🐘', category: 'Wild', sizeClass: 'w-56 h-56', iconSize: 'text-8xl', feedType: 'Vegetation & Hay', growthDays: 'Adult', progressPct: 100, description: 'Highly social megafauna.', companions: ['Buffalo', 'Camel'], enemies: ['Tiger', 'Lion'], careLevel: 'Expert', cost: '$800/mo', water: 'Very High', yieldName: 'Sanctuary Donor ROI', yieldValue: 1000 },
  { id: '19', name: 'Pig', spaceRequired: 25, icon: '🐖', category: 'Livestock', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'Omnivore Mix', growthDays: '180 Days', progressPct: 50, description: 'Highly intelligent and sociable.', companions: ['Cow', 'Sheep', 'Goat', 'Chicken', 'Duck', 'Guard Dog'], enemies: ['Wolf', 'Tiger', 'Bear'], careLevel: 'Intermediate', cost: '$60/mo', water: 'High', yieldName: 'Fertilizer/Truffles', yieldValue: 90 },
  { id: '20', name: 'Alpaca', spaceRequired: 15, icon: '🦙', category: 'Livestock', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'Pasture', growthDays: '365 Days', progressPct: 40, description: 'Produces fine fleece.', companions: ['Llama', 'Sheep', 'Donkey', 'Guard Dog', 'Collie', 'Goat'], enemies: ['Wolf', 'Bear'], careLevel: 'Intermediate', cost: '$50/mo', water: 'Medium', yieldName: 'Premium Fleece', yieldValue: 80 },
  { id: '21', name: 'Llama', spaceRequired: 25, icon: '🦙', category: 'Livestock', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Pasture', growthDays: '365 Days', progressPct: 40, description: 'Larger than alpacas, often guard animals.', companions: ['Alpaca', 'Sheep', 'Goat', 'Guard Dog', 'Collie', 'Donkey'], enemies: ['Wolf', 'Bear'], careLevel: 'Intermediate', cost: '$60/mo', water: 'Medium', yieldName: 'Fleece/Packing', yieldValue: 85 },
  { id: '22', name: 'Turkey', spaceRequired: 8, icon: '🦃', category: 'Poultry', sizeClass: 'w-16 h-16', iconSize: 'text-3xl', feedType: 'Poultry Feed', growthDays: '140 Days', progressPct: 70, description: 'Large poultry bird.', companions: ['Chicken', 'Peacock', 'Duck', 'Goose', 'Guard Dog'], enemies: ['Fox', 'Wolf', 'Cat'], careLevel: 'Intermediate', cost: '$25/mo', water: 'Medium', yieldName: 'Eggs/Feathers', yieldValue: 40 },
  { id: '23', name: 'Goose', spaceRequired: 10, icon: '🪿', category: 'Poultry', sizeClass: 'w-16 h-16', iconSize: 'text-3xl', feedType: 'Grass & Grain', growthDays: '120 Days', progressPct: 80, description: 'Excellent "watchdogs".', companions: ['Duck', 'Chicken', 'Turkey', 'Peacock'], enemies: ['Fox', 'Wolf', 'Cat'], careLevel: 'Intermediate', cost: '$25/mo', water: 'High', yieldName: 'Eggs/Security', yieldValue: 35 },
  { id: '24', name: 'Quail', spaceRequired: 2, icon: '🐦', category: 'Poultry', sizeClass: 'w-10 h-10', iconSize: 'text-lg', feedType: 'Gamebird Feed', growthDays: '40 Days', progressPct: 90, description: 'Small gamebirds.', companions: ['Chicken', 'Duck'], enemies: ['Cat', 'Fox', 'Snake'], careLevel: 'Beginner Friendly', cost: '$10/mo', water: 'Low', yieldName: 'Gourmet Eggs', yieldValue: 20 },
  { id: '25', name: 'Mule', spaceRequired: 60, icon: '🐴', category: 'Working', sizeClass: 'w-32 h-32', iconSize: 'text-5xl', feedType: 'Hay & Grass', growthDays: 'Adult', progressPct: 100, description: 'Strong, hardy hybrid.', companions: ['Horse', 'Donkey', 'Cow', 'Goat', 'Sheep', 'Cat'], enemies: ['Wolf', 'Bear'], careLevel: 'Intermediate', cost: '$120/mo', water: 'High', heavyWork: true, yieldName: 'Draft Power', yieldValue: 160 },
  { id: '26', name: 'Collie', spaceRequired: 30, icon: '🐶', category: 'Working', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'High-Protein Kibble', growthDays: 'Adult', progressPct: 100, description: 'Energetic herding dog.', companions: ['Sheep', 'Goat', 'Guard Dog', 'Alpaca', 'Llama'], enemies: ['Wolf', 'Tiger'], careLevel: 'Advanced', cost: '$80/mo', water: 'Medium', yieldName: 'Herding Labor', yieldValue: 120 },
  { id: '27', name: 'Emu', spaceRequired: 40, icon: '🦤', category: 'Exotic', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Omnivore Pellets', growthDays: '500 Days', progressPct: 80, description: 'Curious Australian flightless bird.', companions: ['Ostrich', 'Kangaroo', 'Camel', 'Deer'], enemies: ['Tiger', 'Lion', 'Wolf'], careLevel: 'Advanced', cost: '$70/mo', water: 'Medium', yieldName: 'Oils/Tourism', yieldValue: 90 },
  { id: '28', name: 'Kangaroo', spaceRequired: 60, icon: '🦘', category: 'Exotic', sizeClass: 'w-32 h-32', iconSize: 'text-5xl', feedType: 'Grass & Shrubs', growthDays: 'Adult', progressPct: 100, description: 'Marsupial grazer.', companions: ['Emu', 'Ostrich', 'Deer'], enemies: ['Lion', 'Tiger', 'Wolf'], careLevel: 'Expert', cost: '$100/mo', water: 'Low', yieldName: 'Eco-Tourism', yieldValue: 130 },
  { id: '29', name: 'Lion', spaceRequired: 250, icon: '🦁', category: 'Wild', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Raw Meat', growthDays: 'Adult', progressPct: 100, description: 'Social apex predators.', companions: [], enemies: ['Buffalo', 'Elephant', 'Ostrich', 'Deer', 'Cow', 'Sheep', 'Goat'], careLevel: 'Expert', cost: '$350/mo', water: 'High', yieldName: 'Conservation Grant', yieldValue: 500 },
  { id: '30', name: 'Bear', spaceRequired: 200, icon: '🐻', category: 'Wild', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Omnivore Diet', growthDays: 'Adult', progressPct: 100, description: 'Massive, highly intelligent omnivores.', companions: [], enemies: ['Horse', 'Cow', 'Deer', 'Sheep', 'Goat', 'Pig', 'Alpaca'], careLevel: 'Expert', cost: '$250/mo', water: 'High', yieldName: 'Conservation Grant', yieldValue: 350 }
]`;

const paths = [
  path.join(__dirname, 'app', 'dashboard', 'page.tsx'),
  path.join(__dirname, 'app', 'dashboard', 'health', 'page.tsx'),
  path.join(__dirname, 'app', 'dashboard', 'encyclopedia', 'page.tsx'),
  path.join(__dirname, 'app', 'api', 'assistant', 'route.ts'),
  path.join(__dirname, 'app', 'page.tsx')
];

paths.forEach(p => {
  if (fs.existsSync(p)) {
    let content = fs.readFileSync(p, 'utf8');
    
    if (p.includes('app\\\\page.tsx') || p.includes('app/page.tsx')) {
      content = content.replace(/const speciesLibrary = \[[\s\S]*?\];/, 'const speciesLibrary = ' + speciesArray + ';');
    } else {
      content = content.replace(/export const speciesLibrary(?:.*?) = \[[\s\S]*?\];/, 'export const speciesLibrary: AnimalSpecies[] = ' + speciesArray + ';');
    }
    
    fs.writeFileSync(p, content);
    console.log('Updated', p);
  } else {
    console.log('File not found:', p);
  }
});
