const fs = require('fs');
const path = require('path');

const speciesArray = `[
  { id: '1', name: 'Sheep', spaceRequired: 20, icon: '🐑', category: 'Livestock', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'Pasture & Hay', growthDays: '150 Days', progressPct: 60, description: 'Provides wool and natural grazing. Excellent for pasture management.', companions: ['Goat', 'Guard Dog', 'Chicken', 'Llama', 'Alpaca', 'Pig'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Beginner Friendly', cost: '$45/mo', water: 'Medium' },
  { id: '2', name: 'Goat', spaceRequired: 15, icon: '🐐', category: 'Livestock', sizeClass: 'w-20 h-20', iconSize: 'text-3xl', feedType: 'Brush & Hay', growthDays: '120 Days', progressPct: 75, description: 'Excellent at clearing brush and weeds. Very curious and active.', companions: ['Sheep', 'Horse', 'Cow', 'Mule', 'Pig'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Intermediate', cost: '$40/mo', water: 'Medium' },
  { id: '3', name: 'Cow', spaceRequired: 60, icon: '🐄', category: 'Livestock', sizeClass: 'w-36 h-36', iconSize: 'text-6xl', feedType: 'Pasture & Silage', growthDays: '700 Days', progressPct: 30, description: 'Large grazing animal. Requires substantial pasture and fencing.', companions: ['Horse', 'Goat', 'Pig', 'Mule'], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Advanced', cost: '$120/mo', water: 'High' },
  { id: '4', name: 'Buffalo', spaceRequired: 70, icon: '🐃', category: 'Livestock', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Grass & Forage', growthDays: '800 Days', progressPct: 20, description: 'Requires very sturdy fencing and access to mud wallows/water.', companions: ['Cow', 'Elephant'], enemies: ['Tiger', 'Lion'], careLevel: 'Advanced', cost: '$150/mo', water: 'Very High' },
  { id: '5', name: 'Horse', spaceRequired: 80, icon: '🐎', category: 'Livestock', sizeClass: 'w-36 h-36', iconSize: 'text-6xl', feedType: 'Hay & Grain', growthDays: 'Adult', progressPct: 100, description: 'Requires large running space, strong fencing, and daily grooming.', companions: ['Goat', 'Cow', 'Donkey', 'Mule'], enemies: ['Wolf', 'Bear'], careLevel: 'Advanced', cost: '$200/mo', water: 'High' },
  { id: '6', name: 'Donkey', spaceRequired: 40, icon: '🫏', category: 'Working', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Hay & Grass', growthDays: 'Adult', progressPct: 100, description: 'Excellent guard animals for livestock. Highly intelligent and hardy.', companions: ['Sheep', 'Horse', 'Alpaca'], enemies: ['Wolf'], careLevel: 'Intermediate', cost: '$50/mo', water: 'Low' },
  { id: '7', name: 'Chicken', spaceRequired: 4, icon: '🐔', category: 'Poultry', sizeClass: 'w-12 h-12', iconSize: 'text-xl', feedType: 'Grain & Crumbles', growthDays: '45 Days', progressPct: 85, description: 'Provides daily eggs and pest control. Needs a secure coop.', companions: ['Duck', 'Sheep', 'Goat', 'Turkey', 'Guinea Fowl'], enemies: ['Cat', 'Wolf', 'Fox'], careLevel: 'Beginner Friendly', cost: '$15/mo', water: 'Low' },
  { id: '8', name: 'Duck', spaceRequired: 6, icon: '🦆', category: 'Poultry', sizeClass: 'w-14 h-14', iconSize: 'text-2xl', feedType: 'Pellets & Greens', growthDays: '50 Days', progressPct: 65, description: 'Excellent for slug control. Requires a water source for bathing.', companions: ['Chicken', 'Goose'], enemies: ['Cat', 'Wolf', 'Fox'], careLevel: 'Beginner Friendly', cost: '$20/mo', water: 'High' },
  { id: '9', name: 'Ostrich', spaceRequired: 45, icon: '🦤', category: 'Poultry', sizeClass: 'w-32 h-32', iconSize: 'text-6xl', feedType: 'Plants & Insects', growthDays: '365 Days', progressPct: 100, description: 'Largest living bird. Very fast, requires strong, tall fencing.', companions: ['Zebra', 'Emu'], enemies: ['Lion', 'Tiger'], careLevel: 'Advanced', cost: '$80/mo', water: 'Low' },
  { id: '10', name: 'Peacock', spaceRequired: 15, icon: '🦚', category: 'Poultry', sizeClass: 'w-20 h-20', iconSize: 'text-4xl', feedType: 'Seeds & Insects', growthDays: '200 Days', progressPct: 90, description: 'Ornamental bird. Needs roosting trees and large aviaries.', companions: ['Chicken', 'Turkey'], enemies: ['Cat', 'Wolf'], careLevel: 'Intermediate', cost: '$30/mo', water: 'Medium' },
  { id: '11', name: 'Guard Dog', spaceRequired: 25, icon: '🐕', category: 'Working', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Meat & Kibble', growthDays: 'Adult', progressPct: 100, description: 'Protects livestock from predators. Highly loyal and alert.', companions: ['Sheep', 'Goat', 'Cow', 'Pig', 'Alpaca'], enemies: ['Wolf', 'Tiger', 'Cat', 'Bear'], careLevel: 'Intermediate', cost: '$60/mo', water: 'Medium' },
  { id: '12', name: 'Cat', spaceRequired: 10, icon: '🐈', category: 'Working', sizeClass: 'w-16 h-16', iconSize: 'text-2xl', feedType: 'Meat & Fish', growthDays: 'Adult', progressPct: 100, description: 'Excellent barn cat for rodent control. Very independent.', companions: ['Horse', 'Cow', 'Pig'], enemies: ['Guard Dog', 'Chicken', 'Parrot', 'Quail'], careLevel: 'Beginner Friendly', cost: '$20/mo', water: 'Low' },
  { id: '13', name: 'Parrot', spaceRequired: 5, icon: '🦜', category: 'Exotic', sizeClass: 'w-12 h-12', iconSize: 'text-xl', feedType: 'Seeds & Fruits', growthDays: 'Adult', progressPct: 100, description: 'Highly intelligent and vocal. Needs extensive enrichment.', companions: [], enemies: ['Cat'], careLevel: 'Advanced', cost: '$40/mo', water: 'Low' },
  { id: '14', name: 'Camel', spaceRequired: 70, icon: '🐪', category: 'Exotic', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Dry Foliage', growthDays: 'Adult', progressPct: 100, description: 'Desert adapted. Requires specialized dry environments.', companions: ['Donkey'], enemies: ['Tiger', 'Lion'], careLevel: 'Intermediate', cost: '$90/mo', water: 'Very Low' },
  { id: '15', name: 'Wolf', spaceRequired: 100, icon: '🐺', category: 'Wild', sizeClass: 'w-32 h-32', iconSize: 'text-6xl', feedType: 'Raw Meat', growthDays: 'Adult', progressPct: 100, description: 'Apex pack predators. Requires highly specialized, fortified enclosures.', companions: [], enemies: ['Guard Dog', 'Sheep', 'Goat', 'Cow', 'Buffalo', 'Horse', 'Pig', 'Llama', 'Alpaca', 'Deer', 'Mule'], careLevel: 'Expert', cost: '$180/mo', water: 'Medium' },
  { id: '16', name: 'Deer', spaceRequired: 150, icon: '🦌', category: 'Wild', sizeClass: 'w-32 h-32', iconSize: 'text-6xl', feedType: 'Forage & Leaves', growthDays: 'Adult', progressPct: 100, description: 'Flighty herbivores that can jump extremely high. Requires 8ft+ fencing and forest cover.', companions: [], enemies: ['Wolf', 'Tiger', 'Bear', 'Lion'], careLevel: 'Advanced', cost: '$90/mo', water: 'Medium' },
  { id: '17', name: 'Tiger', spaceRequired: 200, icon: '🐅', category: 'Wild', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Heavy Meat', growthDays: 'Adult', progressPct: 100, description: 'Massive solitary predators. Extreme containment protocols and vast space required.', companions: [], enemies: ['Cow', 'Buffalo', 'Deer', 'Sheep', 'Goat', 'Horse', 'Pig'], careLevel: 'Expert', cost: '$300/mo', water: 'High' },
  { id: '18', name: 'Elephant', spaceRequired: 500, icon: '🐘', category: 'Wild', sizeClass: 'w-56 h-56', iconSize: 'text-8xl', feedType: 'Vegetation & Hay', growthDays: 'Adult', progressPct: 100, description: 'Highly social megafauna. Needs reinforced containment, massive dietary intake, and social enrichment.', companions: ['Buffalo'], enemies: ['Tiger', 'Lion'], careLevel: 'Expert', cost: '$800/mo', water: 'Very High' },
  { id: '19', name: 'Pig', spaceRequired: 25, icon: '🐖', category: 'Livestock', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'Omnivore Mix', growthDays: '180 Days', progressPct: 50, description: 'Highly intelligent and sociable. Needs mud wallows for cooling.', companions: ['Cow', 'Sheep', 'Goat', 'Chicken'], enemies: ['Wolf', 'Tiger', 'Bear'], careLevel: 'Intermediate', cost: '$60/mo', water: 'High' },
  { id: '20', name: 'Alpaca', spaceRequired: 15, icon: '🦙', category: 'Livestock', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'Pasture', growthDays: '365 Days', progressPct: 40, description: 'Produces fine fleece. Gentle herd animals that require companions.', companions: ['Llama', 'Sheep', 'Donkey'], enemies: ['Wolf', 'Bear'], careLevel: 'Intermediate', cost: '$50/mo', water: 'Medium' },
  { id: '21', name: 'Llama', spaceRequired: 25, icon: '🦙', category: 'Livestock', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Pasture', growthDays: '365 Days', progressPct: 40, description: 'Larger than alpacas, often used as guard animals for smaller livestock.', companions: ['Alpaca', 'Sheep', 'Goat'], enemies: ['Wolf', 'Bear'], careLevel: 'Intermediate', cost: '$60/mo', water: 'Medium' },
  { id: '22', name: 'Turkey', spaceRequired: 8, icon: '🦃', category: 'Poultry', sizeClass: 'w-16 h-16', iconSize: 'text-3xl', feedType: 'Poultry Feed', growthDays: '140 Days', progressPct: 70, description: 'Large poultry bird. Needs sturdy roosts and predator protection.', companions: ['Chicken', 'Peacock'], enemies: ['Fox', 'Wolf', 'Cat'], careLevel: 'Intermediate', cost: '$25/mo', water: 'Medium' },
  { id: '23', name: 'Goose', spaceRequired: 10, icon: '🪿', category: 'Poultry', sizeClass: 'w-16 h-16', iconSize: 'text-3xl', feedType: 'Grass & Grain', growthDays: '120 Days', progressPct: 80, description: 'Excellent "watchdogs" that honk at intruders. Needs water access.', companions: ['Duck'], enemies: ['Fox', 'Wolf'], careLevel: 'Intermediate', cost: '$25/mo', water: 'High' },
  { id: '24', name: 'Quail', spaceRequired: 2, icon: '🐦', category: 'Poultry', sizeClass: 'w-10 h-10', iconSize: 'text-lg', feedType: 'Gamebird Feed', growthDays: '40 Days', progressPct: 90, description: 'Small gamebirds. Require highly secure enclosures to prevent escape.', companions: [], enemies: ['Cat', 'Fox', 'Snake'], careLevel: 'Beginner Friendly', cost: '$10/mo', water: 'Low' },
  { id: '25', name: 'Mule', spaceRequired: 60, icon: '🐴', category: 'Working', sizeClass: 'w-32 h-32', iconSize: 'text-5xl', feedType: 'Hay & Grass', growthDays: 'Adult', progressPct: 100, description: 'Strong, hardy hybrid. Excellent working animal with high stamina.', companions: ['Horse', 'Donkey', 'Cow'], enemies: ['Wolf', 'Bear'], careLevel: 'Intermediate', cost: '$120/mo', water: 'High' },
  { id: '26', name: 'Collie', spaceRequired: 30, icon: '🐶', category: 'Working', sizeClass: 'w-24 h-24', iconSize: 'text-4xl', feedType: 'High-Protein Kibble', growthDays: 'Adult', progressPct: 100, description: 'Energetic herding dog. Essential for managing large sheep flocks.', companions: ['Sheep', 'Goat', 'Guard Dog'], enemies: ['Wolf', 'Tiger'], careLevel: 'Advanced', cost: '$80/mo', water: 'Medium' },
  { id: '27', name: 'Emu', spaceRequired: 40, icon: '🦤', category: 'Exotic', sizeClass: 'w-28 h-28', iconSize: 'text-5xl', feedType: 'Omnivore Pellets', growthDays: '500 Days', progressPct: 80, description: 'Curious Australian flightless bird. Fast runners, need tall fences.', companions: ['Ostrich', 'Kangaroo'], enemies: ['Tiger', 'Lion'], careLevel: 'Advanced', cost: '$70/mo', water: 'Medium' },
  { id: '28', name: 'Kangaroo', spaceRequired: 60, icon: '🦘', category: 'Exotic', sizeClass: 'w-32 h-32', iconSize: 'text-5xl', feedType: 'Grass & Shrubs', growthDays: 'Adult', progressPct: 100, description: 'Marsupial grazer. Can jump extremely high; requires specialized fencing.', companions: ['Emu'], enemies: ['Lion', 'Tiger'], careLevel: 'Expert', cost: '$100/mo', water: 'Low' },
  { id: '29', name: 'Lion', spaceRequired: 250, icon: '🦁', category: 'Wild', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Raw Meat', growthDays: 'Adult', progressPct: 100, description: 'Social apex predators (prides). Extreme security protocols required.', companions: [], enemies: ['Buffalo', 'Elephant', 'Ostrich', 'Deer', 'Cow', 'Sheep'], careLevel: 'Expert', cost: '$350/mo', water: 'High' },
  { id: '30', name: 'Bear', spaceRequired: 200, icon: '🐻', category: 'Wild', sizeClass: 'w-40 h-40', iconSize: 'text-7xl', feedType: 'Omnivore Diet', growthDays: 'Adult', progressPct: 100, description: 'Massive, highly intelligent omnivores. Can climb and dig; extreme containment needed.', companions: [], enemies: ['Horse', 'Cow', 'Deer', 'Sheep', 'Goat', 'Pig'], careLevel: 'Expert', cost: '$250/mo', water: 'High' }
]`;

const paths = [
  path.join(__dirname, 'app', 'dashboard', 'page.tsx'),
  path.join(__dirname, 'app', 'dashboard', 'health', 'page.tsx'),
  path.join(__dirname, 'app', 'dashboard', 'encyclopedia', 'page.tsx'),
  path.join(__dirname, 'app', 'api', 'assistant', 'route.ts'),
  path.join(__dirname, 'app', 'page.tsx')
];

paths.forEach(p => {
  if (fs.existsSync(p)) {
    let content = fs.readFileSync(p, 'utf8');
    
    if (p.includes('app\\\\page.tsx') || p.includes('app/page.tsx')) {
      content = content.replace(/const speciesLibrary = \[[\s\S]*?\];/, 'const speciesLibrary = ' + speciesArray + ';');
    } else {
      content = content.replace(/export const speciesLibrary(?:.*?) = \[[\s\S]*?\];/, 'export const speciesLibrary: AnimalSpecies[] = ' + speciesArray + ';');
    }
    
    fs.writeFileSync(p, content);
    console.log('Updated', p);
  } else {
    console.log('File not found:', p);
  }
});
